name: Lint
run-name: Lint
on:
  - workflow_call # Allowing for calling from other workflows
  - workflow_dispatch # Allowing for manual triggering
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
      - name: ruff check
        run: uv run --extra lint ruff check
      - name: ruff format
        run: uv run --extra lint ruff format --check
