name: testing-and-linting
run-name: Testing and liniting
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[pipeline]
      - name: Run tests
        run: python -m pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[pipepline]
      - name: Linting with flakes8
        run: python -m flake8
      - name: Linting with black
        run: python -m black --check .
      - name: Linting with isort
        run: python -m isort --check .
